### ISSUE TITLE
Design Stores Database

### ISSUE THREAD

**Issue by SirWellington** [BlackSourceLabs/BlackNectar-Service#17]
# Stores

| Field | Type | 
| ------------- |:-------------:| 
| Store ID   | Int (Primary Key)
| Store Name | String
| Latitude | Double
| Longitude | Double
| Location | Geometry
| Address ID | Int
| City | String
| State | String
| Zip 5 | Int

# Users
| Field | Type | 
| ------------- |:-------------:| 
| User ID | Int (Primary Key)
| First Name | String
| Last Name | String
| Email | String
| EBT Card | String
| EBT Benefits | Set<Int>
| Zip | Int
| Last Known Location | Geometry
| Is Working | Boolean
| Age | Int
| Birtday | Date
| Job Industry | String

# Images
| Field | Type | 
| ------------- |:-------------:| 
| URL | String (Primary Key)
| image | binary

**Comment by SirWellington** [comment]
The file we got from the government contains the following:

+ Store Name
+ Longitude
+ Latitude
+ Address Line 1
+ Address Line 2
+ City
+ State
+ Zip5
+ Zip4
+ County

**Comment by SirWellington** [comment]
# Stores

+ Store ID
+ Store Name
+ Latitude
+ Longitude 
+ Location
+ Address Line 1
+ Address Line 2
+ City
+ State
+ Zip 5
+ Zip 4
+ County

**Comment by SirWellington** [comment]
| Field | Type | 
| ------------- |:-------------:| 
| Store ID   | Int
| Store Name | String

**Comment by SirWellington** [comment]
Gonna save the images for another Ticket. One step at a time...

**Comment by cordhernandez** [comment]
roger that
